apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lxxp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-lxxp@sha256:05f6bc8208f50457d6dcccc71a197032dbeb744635051a13edb0fa7373fdd505
        name: my-nodejs
        resources: {}
status: {}
